version: "3.9"
services:
  duty-checker:
    image: duty-checker-api:latest
    container_name: duty-checker
    networks:
      - traefik-net
    ports:
      - "8081:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duty-checker.rule=Host(`duty-checker.guegue.dev`)"
      - "traefik.http.routers.duty-checker.entrypoints=websecure"
      - "traefik.http.routers.duty-checker.tls.certresolver=le"
      - "traefik.http.services.duty-checker.loadbalancer.server.port=8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://group-study-mysql:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_DATA_REDIS_HOST=group-study-redis
      - SPRING_DATA_REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  traefik-net:
    external: true
