spring:
  application:
    name: duty-checker
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-expiration-ms: 3600000     # 1시간
  refresh-expiration-ms: 7776000000 # 90일

coolsms:
  api:
    key: ${COOLSMS_API_KEY}
    secret:
      key: ${COOLSMS_API_SECRET_KEY}
    domain: https://api.coolsms.co.kr
    from-num: ${COOLSMS_FROM_NUM}

server:
  port: 8080

logging:
  level:
    com.guegue.duty_checker: DEBUG
    org.hibernate.SQL: DEBUG
